require "cgi"

p(CGI.escape("a b&c/d?e=f"))
p(CGI.escape("~-_.*+ '\"<>"))
p(CGI.escape(""))
p(CGI.escape("日本語 é😀"))
p(CGI.unescape("a+b%26c%2Fd%3Fe%3Df"))
p(CGI.unescape("%E6%97%A5%E6%9C%AC+%e8%aa%9e"))
p(CGI.unescape("100%"))
p(CGI.unescape("%zz%4"))
p(CGI.unescape(""))
bad = CGI.unescape("%E3%81")
p(bad.valid_encoding?)
p(CGI.unescape(CGI.escape("round trip: 1+1=2 & 日本")))

p(CGI.escapeURIComponent("a b+c"))
p(CGI.escape_uri_component("日本 語"))
p(CGI.unescapeURIComponent("a+b%20c"))
p(CGI.unescape_uri_component("%E6%97%A5"))

p(CGI.escapeHTML("<a href=\"x\">Tom & 'Jerry'</a>"))
p(CGI.escapeHTML(""))
p(CGI.escapeHTML("plain 日本"))
p(CGI.escape_html("a<b"))
p(CGI.unescapeHTML("&lt;p&gt;Tom &amp; &quot;Jerry&quot; &apos;x&#39;&lt;/p&gt;"))
p(CGI.unescapeHTML("&#65;&#x42;&#X43;&#0065; &#x65e5;&#26412; &#x1F600;"))
p(CGI.unescapeHTML("&amp &AMP; &am; &#; &#x; &#xg; &#-1; &nbsp; & alone"))
p(CGI.unescapeHTML("&#x10FFFE;|&#x10FFFF;|&#1114111;|&#x110000;|&#99999999999999999999;"))
p(CGI.unescapeHTML("&amp;lt;"))
p(CGI.unescape_html(CGI.escapeHTML("<&>\"'")))

# the optional encoding of the result
b = CGI.unescape("%E6%97%A5+x", "ASCII-8BIT")
p(b)
p(b.encoding.to_s)
p(CGI.unescape("%E6%97%A5", "UTF-8"))
p(CGI.unescapeURIComponent("%E6%97%A5+", "ASCII-8BIT"))
p(CGI.unescape_uri_component("%41", "UTF-8"))
