#!/bin/sh
# Builds docs/manual/build/index.html (both languages) with ligarb (https://github.com/ko1/ligarb).
# The appendix "Built-in operations" is docs/builtins.md (generated by tools/gen_builtins.rb), copied here
# with its link to spec.md made absolute, since spec.md is not a chapter of the book.
set -e
cd "$(dirname "$0")"
sed 's|\[spec.md\](spec.md)|[spec.md](https://github.com/ko1/sake-lang/blob/main/docs/spec.md)|g; s|\[builtins.md\](builtins.md)|the appendix|g' ../builtins.md > builtins.md
ligarb build book.yml
