# frozen_string_literal: true
require "stringio"

# Builds docs/builtins.md, the complete list of built-in operations, from the registry.
# usage: ruby tools/gen_builtins.rb [--check]   (--check: exit 1 if docs/builtins.md is stale)
require_relative "../lib/sake"

ROOT = File.expand_path("..", __dir__)

def build
  reg = Sake::Registry.new
  Sake::Stdlib.install(reg, StringIO.new)
  Sake::Stdlib.install_ext(reg, StringIO.new, StringIO.new)
  out = +"<!-- Generated by tools/gen_builtins.rb. Do not edit. -->\n\n# Sake-lang built-in operations\n\n"
  out << "Every built-in operation, by namespace. `x` is the subject (an argument of the namespace's type),\n"
  out << "`[T]` an optional argument, `*T` any number of them, `{ }` a required block, and `[{ }]` an optional one.\n"
  out << "The operators are listed in [spec.md](spec.md) (`BinaryOp`, `Index`). Names follow Ruby's core library.\n"
  reg.namespaces.sort.each do |ns|
    names = reg.names(ns)
    next if names.empty?
    out << "\n## #{ns}\n\n"
    names.sort.each { |n| out << "- `#{reg.lookup(ns, n).signature}`\n" }
  end
  out << "\n## Exception types\n\n"
  named, scoped = Sake::Resolver::BUILTIN_EXCEPTIONS.partition { !_1.include?("::") }
  out << "Each of #{named.map { "`#{_1}`" }.join(", ")} has `T.new(message)`, "
  out << "`T.message(x)`, and `T.set_message(x, v)`. `Exception.message(e)` reads the message of any exception; "
  out << "`Exception.new(:field, ...)` declares an exception type ([spec.md](spec.md) §13). "
  out << "#{scoped.map { "`#{_1}`" }.join(", ")} can only be named in `rescue`.\n"
  out
end

if __FILE__ == $0
  require "stringio"
  path = File.join(ROOT, "docs/builtins.md")
  exit(File.exist?(path) && File.read(path) == build ? 0 : 1) if ARGV.include?("--check")
  File.write(path, build)
end
