# frozen_string_literal: true

# Builds docs/tutorial.md from docs/tutorial.src.md by running the examples in docs/examples.
#   @@example NAME [FLAGS...]   the source of NAME.sake, then its actual output
#   @@run NAME [FLAGS...]       only the output of `sake FLAGS NAME.sake`
# usage: ruby tools/gen_tutorial.rb [--check]   (--check: exit 1 if docs/tutorial.md is stale)
require "stringio"
require_relative "../lib/sake/cli"

ROOT = File.expand_path("..", __dir__)
EXAMPLES = File.join(ROOT, "docs/examples")

def run_example(name, flags)
  out = StringIO.new
  err = StringIO.new
  status = Dir.chdir(EXAMPLES) { Sake::CLI.main([*flags, "#{name}.sake"], out:, err:) }
  text = +"$ sake #{[*flags, "#{name}.sake"].join(" ")}\n#{out.string}#{err.string}"
  text << "(exit status #{status})\n" unless status.zero?
  "```\n#{text}```\n"
end

def build
  src = File.read(File.join(ROOT, "docs/tutorial.src.md"))
  src.gsub(/^@@(example|run) (\S+)(.*)\n/) do
    kind = $1
    name = $2
    flags = $3.split
    code = kind == "example" ? "```ruby\n#{File.read(File.join(EXAMPLES, "#{name}.sake"))}```\n\n" : ""
    "#{code}#{run_example(name, flags)}\n"
  end.gsub(/\n{3,}/, "\n\n")
end

if __FILE__ == $0
  generated = "<!-- Generated by tools/gen_tutorial.rb from docs/tutorial.src.md. Do not edit. -->\n\n#{build}"
  path = File.join(ROOT, "docs/tutorial.md")
  if ARGV.include?("--check")
    exit(File.exist?(path) && File.read(path) == generated ? 0 : 1)
  end
  File.write(path, generated)
end
