# frozen_string_literal: true

# Builds docs/cheatsheet.md: Part 1 is docs/cheatsheet.src.md, whose every ```ruby block must run
# clean under --strict=2 (the build fails otherwise); Part 2 is the compact list of built-in
# operations from the registry (one paragraph per namespace, the namespace prefix dropped).
# usage: ruby tools/gen_cheatsheet.rb [--check]   (--check: exit 1 if docs/cheatsheet.md is stale)
require "stringio"
require "open3"
require "tmpdir"
require_relative "../lib/sake"

ROOT = File.expand_path("..", __dir__)
SAKE = File.join(ROOT, "bin/sake")

def verify_examples(src)
  blocks = src.scan(/^```ruby\n(.*?)^```\n/m).flatten
  Dir.mktmpdir("cheatsheet") do |dir|
    blocks.each_with_index do |code, i|
      path = File.join(dir, "ex#{i + 1}.sake")
      File.write(path, code)
      out, err, st = Open3.capture3(RbConfig.ruby, SAKE, "--strict=2", path, stdin_data: "3\n1 2\n", chdir: dir)
      next if st.success? && err.empty?
      abort "cheatsheet example #{i + 1} fails under --strict=2:\n#{code}\n--- output ---\n#{out}#{err}"
    end
  end
  blocks.size
end

def operations
  reg = Sake::Registry.new
  Sake::Stdlib.install(reg, StringIO.new)
  Sake::Stdlib.install_ext(reg, StringIO.new, StringIO.new)
  out = +"## Part 2. Operations\n\n"
  out << "Every built-in operation. `x` is the subject (an argument of the namespace's type), `[T]` an\n"
  out << "optional argument, `*T` any number of them, `{ }` a required block, `[{ }]` an optional one.\n"
  out << "Call them as `Namespace.name(...)`; the namespace is the heading.\n"
  reg.namespaces.sort.each do |ns|
    names = reg.names(ns)
    next if names.empty?
    sigs = names.sort.map { |n| "`#{reg.lookup(ns, n).signature.delete_prefix("#{ns}.")}`" }
    out << "\n### #{ns}\n\n#{sigs.join(" · ")}\n"
  end
  named, scoped = Sake::Resolver::BUILTIN_EXCEPTIONS.partition { !_1.include?("::") }
  out << "\n### Exception types\n\n#{named.map { "`#{_1}`" }.join(" · ")}: each has `T.new(message)`, "
  out << "`T.message(x)`, `T.set_message(x, v)`; `Exception.message(e)` reads any. "
  out << "Only in `rescue`: #{scoped.map { "`#{_1}`" }.join(" · ")}.\n"
  out
end

def build(check: false)
  src = File.read(File.join(ROOT, "docs/cheatsheet.src.md"))
  verify_examples(src) unless check
  "<!-- Generated by tools/gen_cheatsheet.rb from docs/cheatsheet.src.md. Do not edit. -->\n\n#{src}\n#{operations}"
end

if __FILE__ == $0
  path = File.join(ROOT, "docs/cheatsheet.md")
  if ARGV.include?("--check")
    exit(File.exist?(path) && File.read(path) == build(check: true) ? 0 : 1)
  end
  File.write(path, build)
end
